# Neural Networks from Scratch by Ajay kumar Mattigunta

In [9]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

In [10]:
import numpy as np 
import matplotlib.pyplot as plt

In [14]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output) 

2.3


In [15]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3]+ bias
print(output) 

4.8


In [19]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output) 

[4.8, 0.20999999999999996, 3.1449999999999996]


In [21]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

some_value = 0.5 
weight = -0.7
bias = 0.7 

print(some_value*weight) 
print(some_value+bias)


-0.35
1.2


In [23]:
import  numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2 

output = np.dot(inputs, weights) + bias 
print(output)

4.8


In [24]:
import  numpy as np

inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = [2, 3, 0.5]

output = np.dot(inputs, weights) + bias 
print(output)

[4.8 5.8 3.3]


In [28]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases 
print(output)

[4.8   1.21  2.385]


In [30]:
#using batches 
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]] 

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5] 

output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [37]:
#adding another layer let see what happend hear 

inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]] 

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5] 

weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, 0.5],
           [-0.44, 0.73, -0.13]] 

biases2 = [-1, 2, -0.5] 

layer1_output = np.dot(inputs, np.array(weights).T) + biases

layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2

print(layer2_output)

[[ 0.5031   0.9377  -2.03875]
 [ 0.2434  -2.5672  -5.7633 ]
 [-0.99314  1.43412 -0.35655]]


In [46]:
pip install nnfs

Note: you may need to restart the kernel to use updated packages.


In [45]:
#let's jump into ml terminology 

import numpy as np

np.random.seed(10)

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons): 
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense (4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X) 
layer2.forward(layer1.output)
print(layer2.output)

[[-0.07239587  0.02721698]
 [ 0.00023585 -0.01589568]
 [ 0.06273921  0.17898066]]


In [ ]:
import numpy as np
import nnfs 
nnfs.

np.random.seed(10)

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons): 
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense (4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X) 
layer2.forward(layer1.output)
print(layer2.output)

In [ ]:
#Activation functions 

import numpy as np 

np.random.seed(10) 

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

input = [1, 2, -1, 3.3, 2.7, 1.1, 2.2, 


In [47]:
import math

layer_outputs = [4.8, 1.21, 2.385]

E = math.e 

exp_values = [] 

for output in layer_outputs:
    exp_values.append(E**output) 

print(exp_values)

norm_base = sum(exp_values) 
norm_values = [] 

for value in exp_values:
    norm_values.append(value / norm_base) 

print(norm_values) 
print(sum(norm_values)) 



[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [48]:
import math
import numpy as np
import nnfs

layer_outputs = [4.8, 1.21, 2.385]

E = math.e 

exp_values = np.exp(layer_outputs)

norm_values = exp_values / np.sum(exp_values)


print(norm_values) 
print(sum(norm_values)) 

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [53]:
import numpy as np
import nnfs

nnfs.init()

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, 1.81, 0.21],
                 [1.41, 1.051, 0.026]]


exp_values = np.exp(layer_outputs)

print(np.sum(layer_outputs, axis=0, keepdims=True)) 

norm_values  = exp_values / np.sum(exp_values, axis=1, keepdims=True) 
print(norm_values)

[[15.11   4.071  2.621]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.98999345e-01 8.32563422e-04 1.68091656e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [ ]:
import numpy as np
import nnfs

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_softmax:
    def froward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

X, y = spiral_data(samples=100, classes=3) 

dens1 = Layer_Dense(2, 3) 
activation1 = Activation_ReLU() 

dens2 = Layer_Dense(3, 3) 
activation1 = Activation_softmax() 

dens1.forward(X)  
activation1.forward(dense1.output) 

dens2.forward(ativation1.output) 
activation2.forward(dense2.output) 

print(dens2)


In [ ]:
import math 

softmax_output = [0.7, 0.1, 0.2] 
target_output = [1, 0, 0] 

loss = .(math. log(softmax_output[0])*target_output[0] + 
        math. log(softmax_output[1])*target_output[1] + 
        math. log(softmax_output[2])*target_output[2]) 
print(loss) 
loss = .math.log(softmax_output[0]) 
print(loss)

In [ ]:
import numpy as np 

softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4], 
                            [0.02, 0.9, 0.08]]) 

class_targets = [0, 1, 1] 

print(np.log(softmax_outputs[[0, 1, 2], [class_targets]]))) 
